<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace Example\Person;

use UnexpectedValueException;

/**
 * Protobuf type <code>example.Person.Skills</code>
 */
class Skills
{
    /**
     * Generated from protobuf enum <code>GOLANG = 0;</code>
     */
    const GOLANG = 0;
    /**
     * Generated from protobuf enum <code>PYTHON = 1;</code>
     */
    const PYTHON = 1;
    /**
     * Generated from protobuf enum <code>JAVA = 2;</code>
     */
    const JAVA = 2;
    /**
     * Generated from protobuf enum <code>RUST = 3;</code>
     */
    const RUST = 3;
    /**
     * Generated from protobuf enum <code>CPP = 4;</code>
     */
    const CPP = 4;

    private static $valueToName = [
        self::GOLANG => 'GOLANG',
        self::PYTHON => 'PYTHON',
        self::JAVA => 'JAVA',
        self::RUST => 'RUST',
        self::CPP => 'CPP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Skills::class, \Example\Person_Skills::class);

