<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a0b68656c6c6f2e70726f746f12076578616d706c65221c0a0c48" .
            "656c6c6f52657175657374120c0a046e616d65180120012809222b0a0a48" .
            "656c6c6f5265706c79120f0a076d657373616765180120012809120c0a04" .
            "74696d6518022001280932430a0548656c6c6f123a0a0a48656c6c6f576f" .
            "726c6412152e6578616d706c652e48656c6c6f526571756573741a132e65" .
            "78616d706c652e48656c6c6f5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

