<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace Example;

if (false) {
    /**
     * This class is deprecated. Use Example\Person\Skills instead.
     * @deprecated
     */
    class Person_Skills {}
}
class_exists(Person\Skills::class);
@trigger_error('Example\Person_Skills is deprecated and will be removed in the next major release. Use Example\Person\Skills instead', E_USER_DEPRECATED);

