<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace Example;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *message 用来定义一个数据结构
 *repeated 的使用：被 repeated 标识的字段可以理解为是一个数组
 *enum 类型使用：枚举用来表示一定范围内具有相同属性的值
 *message 类型的使用： message 在定义过程中是可以声明自己定义的 message 类型
 *map 类型的使用：message 定义时可以使用 map 类型
 *
 * Generated from protobuf message <code>example.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     *年龄
     *
     * Generated from protobuf field <code>int64 age = 1;</code>
     */
    protected $age = 0;
    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string realname = 2;</code>
     */
    protected $realname = '';
    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 3;</code>
     */
    protected $sex = '';
    /**
     *上班交通工具 可以有多份工作 string 类型的
     *
     * Generated from protobuf field <code>repeated string vehicle = 4;</code>
     */
    private $vehicle;
    /**
     *技能 枚举用来表示一定范围内具有相同属性的值
     *
     * Generated from protobuf field <code>.example.Person.Skills skill = 5;</code>
     */
    protected $skill = 0;
    /**
     *工作日 message 在定义过程中是可以声明自己定义的 message 类型
     *
     * Generated from protobuf field <code>.example.WorkDays workDay = 6;</code>
     */
    protected $workDay = null;
    /**
     *挂靠部门 map 类型的使用：message 定义时可以使用 map 类型
     *
     * Generated from protobuf field <code>map<string, .example.Department> dept = 7;</code>
     */
    private $dept;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $age
     *          年龄
     *     @type string $realname
     *          真实姓名
     *     @type string $sex
     *          性别
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $vehicle
     *          上班交通工具 可以有多份工作 string 类型的
     *     @type int $skill
     *          技能 枚举用来表示一定范围内具有相同属性的值
     *     @type \Example\WorkDays $workDay
     *          工作日 message 在定义过程中是可以声明自己定义的 message 类型
     *     @type array|\Google\Protobuf\Internal\MapField $dept
     *          挂靠部门 map 类型的使用：message 定义时可以使用 map 类型
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Person::initOnce();
        parent::__construct($data);
    }

    /**
     *年龄
     *
     * Generated from protobuf field <code>int64 age = 1;</code>
     * @return int|string
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     *年龄
     *
     * Generated from protobuf field <code>int64 age = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt64($var);
        $this->age = $var;

        return $this;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string realname = 2;</code>
     * @return string
     */
    public function getRealname()
    {
        return $this->realname;
    }

    /**
     *真实姓名
     *
     * Generated from protobuf field <code>string realname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRealname($var)
    {
        GPBUtil::checkString($var, True);
        $this->realname = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 3;</code>
     * @return string
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>string sex = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->sex = $var;

        return $this;
    }

    /**
     *上班交通工具 可以有多份工作 string 类型的
     *
     * Generated from protobuf field <code>repeated string vehicle = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    /**
     *上班交通工具 可以有多份工作 string 类型的
     *
     * Generated from protobuf field <code>repeated string vehicle = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVehicle($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->vehicle = $arr;

        return $this;
    }

    /**
     *技能 枚举用来表示一定范围内具有相同属性的值
     *
     * Generated from protobuf field <code>.example.Person.Skills skill = 5;</code>
     * @return int
     */
    public function getSkill()
    {
        return $this->skill;
    }

    /**
     *技能 枚举用来表示一定范围内具有相同属性的值
     *
     * Generated from protobuf field <code>.example.Person.Skills skill = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSkill($var)
    {
        GPBUtil::checkEnum($var, \Example\Person_Skills::class);
        $this->skill = $var;

        return $this;
    }

    /**
     *工作日 message 在定义过程中是可以声明自己定义的 message 类型
     *
     * Generated from protobuf field <code>.example.WorkDays workDay = 6;</code>
     * @return \Example\WorkDays
     */
    public function getWorkDay()
    {
        return $this->workDay;
    }

    /**
     *工作日 message 在定义过程中是可以声明自己定义的 message 类型
     *
     * Generated from protobuf field <code>.example.WorkDays workDay = 6;</code>
     * @param \Example\WorkDays $var
     * @return $this
     */
    public function setWorkDay($var)
    {
        GPBUtil::checkMessage($var, \Example\WorkDays::class);
        $this->workDay = $var;

        return $this;
    }

    /**
     *挂靠部门 map 类型的使用：message 定义时可以使用 map 类型
     *
     * Generated from protobuf field <code>map<string, .example.Department> dept = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getDept()
    {
        return $this->dept;
    }

    /**
     *挂靠部门 map 类型的使用：message 定义时可以使用 map 类型
     *
     * Generated from protobuf field <code>map<string, .example.Department> dept = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setDept($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \hello\Example\Department::class);
        $this->dept = $arr;

        return $this;
    }

}

