<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace HelloWorld;
/**
 * service HelloClient{}
 * 编写 (gprc 定义 Hello 服务)的客户端
 */
class HelloClient extends \Grpc\BaseStub{

    public function __construct($hostname, $opts, $channel = null) {
        parent::__construct($hostname, $opts, $channel);
    }

    /**
     * rpc SayTest(TestRequest) returns (TestReply) {}
     * 方法名尽量和 (gprc 定义 Xuexitest 服务)的方法一样
     * 用于请求和响应该服务
     */
    public function HelloWorld(HelloRequest $argument,$metadata=[],$options=[]){
        return $this->_simpleRequest('/helloWorld.Hello/HelloWorld',
            $argument,
            ['HelloWorld\HelloReply', 'decode'],
            $metadata, $options);
    }

}